logging:
  file:
    history: 7
    name: logs/docuitservice.log
    totalSizeCap: 100MB
  level:
    com:
      example: DEBUG
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
server:
  port: 8081
  servlet:
    context-path: /dockitservice

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/docuit-local
    username: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  main:
    allow-bean-definition-overriding: true
    
  jackson:
    serialization:
      fail-on-empty-beans: false

mail:  
  host: smtp.gmail.com
  port: 587
  username: manikanna49@gmail.com
  password: rihvtnzzcumcaiqe
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

aws:
  accessKey: AKIAYNN3IWMXH2ABQH77
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  region: ap-south-1
  s3:
    bucket: docuit-dev
  secretKey: FGDsCjqJf1Mqut8IUXjUtlBIyrQpQfzxWkX1FMjh
  sns:
    message:
      accessKey: AKIAYNN3IWMXH2ABQH77
      secretKey: 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
      senderId: DOCUIT

sms:
  verifyOTP:
    template: sms/VerificationOTP.ftl
    
image:
  upload:
    documentFolderName: dockit/

profile:
  upload:
    image: profile/