package com.docuitservice.util;

import java.util.Collections;

public class DockItConstants {

	public static final String SIMPLE_DATE_FORMAT = "yyyy-MM-dd HH:mm:ss";
	public static final String TIME_ZONE_DATE_FORMAT = "MM/dd/yyyy HH:mm:ss";
	public static final String RESPONSE_SUCCESS = "SUCCESS";
	public static final String RESPONSE_FAIL = "FAIL";
	public static final Object RESPONSE_EMPTY_DATA = Collections.<String, Object>emptyMap();
	public static final String TOKEN_EXPIRED = "Token is expired";
	public static final String AUTHENTICATION_FAILED = "Authentication failed";
	public static final String FETCH_DATA = "Data Fetched";
	public static final String USER_REGISTERED_SUCCESSFULLY = "User registered successfully and OTP sent to your mobile number";
	public static final String USER_ID_IS_REQUIRED = "UserId is required";
	public static final String FILES_IS_REQUIRED = "Files is required";
	public static final String ADMIN_ROLE_USER = "adminUser";
	public static final String PASSWORD_CHANGED = "Password changed successfully";
	public static final String ROLE_ADMIN_USER = "adminUser";
	public static final String NOTIFICATION_MAIL_TYPE = "MAIL";
	public static final String SERVER_ERROR = "Internal Server Error";
	public static final String EMAIL_IS_REQUIRED = "Email id is required";
	public static final String EMAIL_OTP_RESEND = "Verification code sent successfully to your email id";
	public static final String ROLE_USER = "user";
	public static final String CODE_IS_REQUIRED = "Code is required";
	public static final String EMAIL_NOT_FOUND = "Email id not found";
	public static final String EMAIL_OTP_VERIFIED = "EMAIL OTP VERIFIED";
	public static final String MOBILE_OTP_VERIFIED = "MOBILE OTP VERIFIED";
	public static final String EMAIL_VERIFIED = "Email code verified";
	public static final String MOBILE_VERIFIED = "Mobile otp verified";
	public static final String MOBILE_OTP_EXPIRED = "MOBILE OTP EXPIRED";
	public static final String MAIL_OTP_EXPIRED = "EMAIL OTP EXPIRED";
	public static final String MAIL_OTP_IS_EXPIRED = "Mobile otp is expired";
	public static final String EMAIL_OTP_IS_EXPIRED = "Email otp is expired";
	public static final String USER_CREATED = "CREATED";
	public static final String OTP_SENT = "OTP_SENT";
	public static final String OTP_VERIFIED = "VERIFIED";
	public static final String PENDING_VERIFICATION = "PENDING";
	public static final String ACTIVE = "ACTIVE";
	public static final String PIN_GENERATED = "PIN_GENERATED";
	public static final String PIN_GENERATED_SUCCESSFULLY = "Pin number generated successfully";
	public static final String PIN_NUMBER_IS_WRONG = "Pin number is wrong";
	public static final String FAMILY_REGISTERED_SUCCESSFULLY = "Family registered successfully";
	public static final String FAMILY_NAME_CHANGED_SUCCESSFULLY = "Family name changed successfully";
	public static final String PIN_RESET_SUCCESSFULLY = "Pin reset successfully";
	public static final String PIN_VERIFIED_SUCCESSFULLY = "Pin verified successfully";
	public static final String INVALID_PIN = "Invalid pin";
	public static final String PIN_CHANGED_SUCCESSFULLY = "Pin changed successfully";
	public static final String CATEGORY_NAME_REGISTERED_SUCCESSFULLY = "Category name registered successfully";
	public static final String NOTIFICATION_SMS_TYPE = "SMS";
	public static final String SMS_TYPE = "OTP";
	public static final String SMS_DEFAULT_COUNTRY_CODE = "+91";
	public static final String SMS_TRANSCTION_TYPE = "Transactional";
	public static final String CATEGORY_UPDATED_SUCCESSFULLY = "Category updated successfully";
	public static final String DEVICE_ID_ALREADY_REGISTERED = "This deviceId already registered, please login";
	public static final String NOT_INVITE = "Not invite";
	public static final String FORGOT_PIN_RESET_SUCCESSFULLY = "A PIN reset link has been sent to your registered mobile/email id";
	public static final String DOCUMENT_SHARED_SUCCESFULLY = "Document shared successfully";
	public static final String DOCUMENT_SAVED_SUCCESFULLY = "Document saved successfully";
	public static final String DOCUMENT_REVOKED_SUCCESFULLY = "Document access revoked successfully";
	public static final String DOCUMENT_DELETED_SUCCESFULLY = "Document deleted successfully";
	public static final String DOCUMENT_DELETION_UNSUCCESFULLY = "Document deletion was unsuccessfully";
	public static final int DOCUMENT_NAME_LENGTH = 30;
	public static final String INVITE_REQUESTED = "Invited";
	public static final String INVITE_ACCEPTED = "Accepted";
	public static final String INVITE_REJECTED = "rejected";
	public static final String USER_INVITED_SUCCESSFULY = "User invited successfully";
	public static final String USER_INVITE_RESPONDED = "User invite responded";
	public static final String MOBILE_OTP_RESEND = "Verification otp sent successfully to your mobile number";
	public static final String EMAIL_CODE_RESEND_STATUS = "EMAIL CODE RESEND";
	public static final String MOBILE_OTP_RESEND_STATUS = "MOBILE OTP RESEND";
	public static final String USER_INVITE_DETAILS = "User invite details";
	public static final String FAMILY_MEMBERS_LIST = "Family members list";
	public static final String INVITES_PENDING_LIST = "Invites pending";

}
